# Tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# tests suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = py311
toxworkdir={toxinidir}/.tox

[testenv]
pass_env=
    TELETHON_BOT_NAME
    TELETHON_BOT_TOKEN
    TELETHON_API_PHONE
    TELETHON_API_ID
    TELETHON_API_HASH
    TELETHON_USER_ID
    TELETHON_BOT_ID
    KUCOIN_API_SECRET
    KUCOIN_API_KEY
    KUCOIN_API_KEY_PASSPHRASE
    MEXC_API_KEY
    MEXC_API_SECRET
    OPENAI_API_KEY
    DATABASE_URL
    TEST_DATABASE_URL
    CRYPTO_PANIC_API_KEY
    GNEWS_API_KEY
    MINIO_ACCESS_KEY
    MINIO_SECRET_KEY
    MINIO_ENDPOINT
    MINIO_SECURE
    LOCAL_STORAGE_IS_ENABLED
    LOCAL_STORAGE_PATH
deps =
    requests==2.31.0
    python-telegram-bot==21.4
    telethon==1.36.0
    kucoin-python==1.0.23
    asyncio==3.4.3
    pymexc==1.0.11
    binance-connector==3.8.1
    mplfinance==0.12.10b0
    openai==1.97.1
    pyharmonics==1.5.3
    asyncpg==0.30.0
    python-dotenv==1.1.1
    tiktoken==0.9.0
    minio==7.2.0
commands =
    python3 ./main.py

[testenv:technical-analysis-tests]
pass_env=
    TELETHON_BOT_NAME
    TELETHON_BOT_TOKEN
    TELETHON_API_PHONE
    TELETHON_API_ID
    TELETHON_API_HASH
    TELETHON_USER_ID
    TELETHON_BOT_ID
    KUCOIN_API_SECRET
    KUCOIN_API_KEY
    KUCOIN_API_KEY_PASSPHRASE
    MEXC_API_KEY
    MEXC_API_SECRET
    OPENAI_API_KEY
    DATABASE_URL
    TEST_DATABASE_URL
    CRYPTO_PANIC_API_KEY
    GNEWS_API_KEY
    MINIO_ACCESS_KEY
    MINIO_SECRET_KEY
    MINIO_ENDPOINT
    MINIO_SECURE
    LOCAL_STORAGE_IS_ENABLED
    LOCAL_STORAGE_PATH
deps =
    requests==2.31.0
    python-telegram-bot==21.4
    telethon==1.36.0
    kucoin-python==1.0.23
    asyncio==3.4.3
    pymexc==1.0.11
    binance-connector==3.8.1
    mplfinance==0.12.10b0
    openai==1.97.1
    pyharmonics==1.5.3
    asyncpg==0.30.0
    python-dotenv==1.1.1
    tiktoken==0.9.0
    minio==7.2.0
commands =
    python3 tests.py --set-testset test.technical_analysis

[testenv:fundamental-analysis-tests]
pass_env=
    TELETHON_BOT_NAME
    TELETHON_BOT_TOKEN
    TELETHON_API_PHONE
    TELETHON_API_ID
    TELETHON_API_HASH
    TELETHON_USER_ID
    TELETHON_BOT_ID
    KUCOIN_API_SECRET
    KUCOIN_API_KEY
    KUCOIN_API_KEY_PASSPHRASE
    MEXC_API_KEY
    MEXC_API_SECRET
    OPENAI_API_KEY
    DATABASE_URL
    TEST_DATABASE_URL
    CRYPTO_PANIC_API_KEY
    GNEWS_API_KEY
    MINIO_ACCESS_KEY
    MINIO_SECRET_KEY
    MINIO_ENDPOINT
    MINIO_SECURE
    LOCAL_STORAGE_IS_ENABLED
    LOCAL_STORAGE_PATH
deps =
    requests==2.31.0
    python-telegram-bot==21.4
    telethon==1.36.0
    kucoin-python==1.0.23
    asyncio==3.4.3
    pymexc==1.0.11
    binance-connector==3.8.1
    mplfinance==0.12.10b0
    openai==1.97.1
    pyharmonics==1.5.3
    asyncpg==0.30.0
    python-dotenv==1.1.1
    tiktoken==0.9.0
    minio==7.2.0
commands =
    python3 tests.py --set-testset test.fundamental_analysis

[testenv:pump-tests]
pass_env=
    TELETHON_BOT_NAME
    TELETHON_BOT_TOKEN
    TELETHON_API_PHONE
    TELETHON_API_ID
    TELETHON_API_HASH
    TELETHON_USER_ID
    TELETHON_BOT_ID
    KUCOIN_API_SECRET
    KUCOIN_API_KEY
    KUCOIN_API_KEY_PASSPHRASE
    MEXC_API_KEY
    MEXC_API_SECRET
deps =
    requests==2.31.0
    python-telegram-bot==21.4
    telethon==1.36.0
    kucoin-python==1.0.23
    asyncio==3.4.3
    pymexc==1.0.11
    binance-connector==3.8.1
    mplfinance==0.12.10b0
    pyharmonics==1.5.3
    python-dotenv==1.1.1
    minio==7.2.0
commands =
    python3 tests.py --set-testset test.pump


