---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pump-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pump-bot-api-tests
  template:
    metadata:
      labels:
        app: pump-bot-api-tests
    spec:
      initContainers:
        - name: python-requirements-install
          image: python:3.13.0
          command:
            - /bin/bash
            - -c
            - |
              apt update -y;
              apt upgrade -y;
              apt install python3-pip -y
              pip3 install --upgrade pip setuptools;
              pip3 install tox;
        - name: clone-repo
          image: alpine/git
          command:
            - "sh"
            - "-c"
            - >
              git clone <<pump.bot.repo.url>> ./pump.bot;
          volumeMounts:
            - name: pump-bot-storage
              mountPath: /pump.bot
      containers:
        - name: pump-bot-api-tests
          image: python:3.13.0
          command:
            - /bin/bash
            - -c
            - |
              . ./.env;
              python -m tox -e api-tests;
          volumeMounts:
            - name: pump-bot-storage
              mountPath: /app
            - name: config-volume
              mountPath: /
              subPath: .env
      volumes:
        - name: pump-bot-storage
          persistentVolumeClaim:
            claimName: pvc-pump-bot
        - name: config-volume
          configMap:
            name: pump-bot-config
            items:
              - key: .env
                path: .env
