---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pump-bot
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /k8s/pv/pump-bot
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s.node.001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pump-bot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-pump-bot
