"""
Unit testy src/security.py - bez bazy, sieci i credentiali, wiec moga byc twarda bramka
(PRE-MERGE) w Jenkinsfile.build. Testy integracyjne (tests/technical_analysis_tests) wymagaja
prawdziwej bazy i kluczy gield - te ida do POST-MERGE.
"""

import time
import unittest
from unittest import mock

from starlette.requests import Request

from src.security import (
    CSRFTokenManager,
    InputSanitizer,
    RateLimiter,
    constant_time_compare,
    generate_secure_token,
    validate_password_strength,
)


def make_request(headers=None, client=("10.0.0.1", 12345)):
    scope = {
        "type": "http",
        "method": "GET",
        "path": "/",
        "headers": [(k.lower().encode(), v.encode()) for k, v in (headers or {}).items()],
        "client": client,
    }
    return Request(scope)


class TestCSRFTokenManager(unittest.TestCase):
    def setUp(self):
        CSRFTokenManager.set_secret_key("unit-test-secret")
        CSRFTokenManager._token_cache.clear()

    def test_generated_token_validates_for_same_session(self):
        token = CSRFTokenManager.generate_token("session-a")
        self.assertTrue(CSRFTokenManager.validate_token(token, "session-a"))
        self.assertIn("session-a", CSRFTokenManager._token_cache)

    def test_token_bound_to_session(self):
        token = CSRFTokenManager.generate_token("session-a")
        self.assertFalse(CSRFTokenManager.validate_token(token, "session-b"))

    def test_anonymous_token(self):
        token = CSRFTokenManager.generate_token()
        self.assertTrue(CSRFTokenManager.validate_token(token))
        self.assertEqual(CSRFTokenManager._token_cache, {})

    def test_tampered_signature_rejected(self):
        timestamp, random_bytes, signature = CSRFTokenManager.generate_token("s").split(".")
        forged = f"{timestamp}.{random_bytes}.{'0' * len(signature)}"
        self.assertFalse(CSRFTokenManager.validate_token(forged, "s"))

    def test_malformed_tokens_rejected(self):
        for token in ["", "abc", "a.b", "a.b.c.d", "notanumber.x.y"]:
            with self.subTest(token=token):
                self.assertFalse(CSRFTokenManager.validate_token(token, "s"))

    def test_expired_token_rejected(self):
        token = CSRFTokenManager.generate_token("s")
        later = time.time() + CSRFTokenManager.TOKEN_LIFETIME + 1
        with mock.patch("src.security.time.time", return_value=later):
            self.assertFalse(CSRFTokenManager.validate_token(token, "s"))

    def test_different_secret_rejects_token(self):
        token = CSRFTokenManager.generate_token("s")
        CSRFTokenManager.set_secret_key("rotated-secret")
        self.assertFalse(CSRFTokenManager.validate_token(token, "s"))

    def test_cache_cleanup_drops_expired_entries(self):
        CSRFTokenManager._token_cache["old"] = ("t", time.time() - CSRFTokenManager.TOKEN_LIFETIME - 1)
        CSRFTokenManager.generate_token("fresh")
        self.assertNotIn("old", CSRFTokenManager._token_cache)
        self.assertIn("fresh", CSRFTokenManager._token_cache)

    def test_secret_autogenerated_when_unset(self):
        CSRFTokenManager._secret_key = None
        token = CSRFTokenManager.generate_token()
        self.assertIsNotNone(CSRFTokenManager._secret_key)
        self.assertTrue(CSRFTokenManager.validate_token(token))


class TestRateLimiter(unittest.TestCase):
    def test_blocks_after_limit_plus_burst(self):
        limiter = RateLimiter(requests_per_minute=3, burst_size=2, block_duration_seconds=60)
        request = make_request()
        for _ in range(5):
            self.assertEqual(limiter.is_allowed(request), (True, None))
        self.assertEqual(limiter.is_allowed(request), (False, 60))
        allowed, retry_after = limiter.is_allowed(request)
        self.assertFalse(allowed)
        self.assertLessEqual(retry_after, 60)

    def test_unblocks_after_block_duration(self):
        limiter = RateLimiter(requests_per_minute=1, burst_size=0, block_duration_seconds=10)
        request = make_request()
        limiter.is_allowed(request)
        self.assertFalse(limiter.is_allowed(request)[0])
        with mock.patch("src.security.time.time", return_value=time.time() + 120):
            self.assertEqual(limiter.is_allowed(request), (True, None))

    def test_limits_are_per_client_and_endpoint(self):
        limiter = RateLimiter(requests_per_minute=1, burst_size=0)
        a, b = make_request(client=("1.1.1.1", 1)), make_request(client=("2.2.2.2", 1))
        self.assertTrue(limiter.is_allowed(a)[0])
        self.assertTrue(limiter.is_allowed(b)[0])
        self.assertTrue(limiter.is_allowed(a, endpoint="/login")[0])
        self.assertFalse(limiter.is_allowed(a)[0])

    def test_client_ip_resolution(self):
        limiter = RateLimiter()
        self.assertEqual(limiter._get_client_ip(make_request({"X-Forwarded-For": "9.9.9.9, 10.0.0.1"})), "9.9.9.9")
        self.assertEqual(limiter._get_client_ip(make_request({"X-Real-IP": "8.8.8.8"})), "8.8.8.8")
        self.assertEqual(limiter._get_client_ip(make_request()), "10.0.0.1")
        self.assertEqual(limiter._get_client_ip(make_request(client=None)), "unknown")

    def test_remaining_requests(self):
        limiter = RateLimiter(requests_per_minute=5, burst_size=0)
        request = make_request()
        self.assertEqual(limiter.get_remaining_requests(request), 5)
        limiter.is_allowed(request)
        limiter.is_allowed(request)
        self.assertEqual(limiter.get_remaining_requests(request), 3)


class TestInputSanitizer(unittest.TestCase):
    def test_sanitize_string_escapes_and_trims(self):
        self.assertEqual(InputSanitizer.sanitize_string("  <b>\"x\"</b> "), "&lt;b&gt;&quot;x&quot;&lt;/b&gt;")
        self.assertEqual(InputSanitizer.sanitize_string("abcdef", max_length=3), "abc")
        self.assertEqual(InputSanitizer.sanitize_string(""), "")
        self.assertIsNone(InputSanitizer.sanitize_string(None))

    def test_sanitize_html_strips_dangerous_patterns(self):
        dirty = '<script>alert(1)</script><a href="javascript:x" onclick="y">ok</a>'
        clean = InputSanitizer.sanitize_html(dirty)
        for fragment in ("script", "javascript:", "onclick"):
            self.assertNotIn(fragment, clean)
        self.assertIn("ok", clean)
        self.assertEqual(InputSanitizer.sanitize_html(""), "")

    def test_is_safe_string(self):
        self.assertTrue(InputSanitizer.is_safe_string("BTC/USDT 1d"))
        self.assertTrue(InputSanitizer.is_safe_string(""))
        for payload in ["<iframe src=x>", "vbscript:msgbox", "data:text/html;base64,AAA", "width: expression(alert(1))"]:
            with self.subTest(payload=payload):
                self.assertFalse(InputSanitizer.is_safe_string(payload))

    def test_sanitize_filename(self):
        self.assertEqual(InputSanitizer.sanitize_filename("../../etc/passwd"), "passwd")
        self.assertEqual(InputSanitizer.sanitize_filename("C:\\tmp\\a<b>.png"), "ab.png")
        self.assertEqual(InputSanitizer.sanitize_filename(""), "unnamed")
        self.assertEqual(InputSanitizer.sanitize_filename('<>:"|?*'), "unnamed")
        long_name = InputSanitizer.sanitize_filename("a" * 300 + ".png", max_length=20)
        self.assertEqual(len(long_name), 20)
        self.assertTrue(long_name.endswith(".png"))
        self.assertEqual(InputSanitizer.sanitize_filename("b" * 30, max_length=10), "b" * 10)

    def test_sanitize_nested_structures(self):
        data = {"<k>": ["<v>", {"n": "<x>"}, [1, "<y>"], 2], "num": 1, "d": {"s": "<z>"}}
        self.assertEqual(
            InputSanitizer.sanitize_dict(data),
            {"&lt;k&gt;": ["&lt;v&gt;", {"n": "&lt;x&gt;"}, [1, "&lt;y&gt;"], 2], "num": 1, "d": {"s": "&lt;z&gt;"}},
        )
        self.assertEqual(InputSanitizer.sanitize_dict("not a dict"), "not a dict")
        self.assertEqual(InputSanitizer.sanitize_list("not a list"), "not a list")


class TestSecurityUtilities(unittest.TestCase):
    def test_password_strength(self):
        self.assertEqual(validate_password_strength("Str0ngPassword"), (True, []))
        ok, errors = validate_password_strength("short")
        self.assertFalse(ok)
        self.assertEqual(len(errors), 3)  # dlugosc, wielka litera, cyfra
        ok, errors = validate_password_strength("A1" + "a" * 200)
        self.assertFalse(ok)
        self.assertEqual(len(errors), 1)

    def test_generate_secure_token(self):
        self.assertEqual(len(generate_secure_token()), 64)
        self.assertEqual(len(generate_secure_token(8)), 16)
        self.assertNotEqual(generate_secure_token(), generate_secure_token())

    def test_constant_time_compare(self):
        self.assertTrue(constant_time_compare("abc", "abc"))
        self.assertFalse(constant_time_compare("abc", "abd"))


if __name__ == "__main__":
    unittest.main()
